project/project/Scripts/daily_income_expense/account/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',v.home),
    path('register',v.register_view,name='reg'),
    path('login',v.login_view,name='login'),
    path('logout',v.logout_view,name='logout'),
]

project/project/Scripts/daily_income_expense/daily_income_expense/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('account.urls','account'),namespace='accountapp')),
    path('',include(('income.urls','income'),namespace='incomeapp')),
    path('',include(('expense.urls','expense'),namespace='expenseapp')),
]

project/project/Scripts/daily_income_expense/expense/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addexpense',v.add_expense,name='addexp'),
    path('expenselist',v.expense_list,name='explist'),
    path('delete1/<int:expid>',v.delete_exp),
    path('expense_search',v.expense_search,name='expense_search'),
    path('exp/<str:ext2>',v.sort_by_expensetype,name='ext1')
    
]

project/project/Scripts/daily_income_expense/income/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addincome',v.add_income,name='addinc'),
    path('incomelist',v.income_list,name='inclist'),
    path('delete/<int:inid>',v.delete_inc),
    path('income_search',v.income_search,name='income_search'),
    path('income/<str:inct2>',v.sort_by_incometype,name='inct1')
    
    
]

project/project/Scripts/daily_income_expense/account/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
# Create your models here.
from django import forms
class loginform(forms.Form):
    username=forms.CharField(max_length=30)
    password=forms.CharField(max_length=30,widget=forms.PasswordInput)

project/project/Scripts/daily_income_expense/expense/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Expense(models.Model):
    expense=models.IntegerField()
    expense_type=models.CharField(max_length=30)
    expense_date=models.DateField()
    description=models.TextField(max_length=100)
    user=models.ForeignKey(User,on_delete=models.CASCADE)


    class Meta:
        db_table='expense'

from django import forms
class expenseform(forms.ModelForm):
    class Meta:
        model=Expense
        fields='__all__'

project/project/Scripts/daily_income_expense/income/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class income(models.Model):
    income=models.IntegerField()
    income_type=models.CharField(max_length=30)
    income_date=models.DateField()
    description=models.TextField(max_length=100)
    user=models.ForeignKey(User,on_delete=models.CASCADE)


    class Meta:
        db_table='income'

from django import forms
class incomeform(forms.ModelForm):
    class Meta:
        model=income
        fields='__all__'

project/project/Scripts/daily_income_expense/account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm

from django.contrib.auth import authenticate,login,logout
# Create your views here.
def home(request):
    context={'bal':get_balance(request)}
    return render(request,'home.html',context)

def register_view(request):
    if request.method=='POST':
        f=UserCreationForm(request.POST)
        f.save()
        return redirect('/')

    else:
        f=UserCreationForm
        context={'form':f}
        return render(request,'reg.html',context)
    
from .models import loginform
def login_view(request):
    if request.method=='POST':
        uname=request.POST.get('username')
        passw=request.POST.get('password')
        user=authenticate(request,username=uname,password=passw)

        if user is not None:
            request.session['uid']=user.id
            login(request,user)
            return redirect('/')
        else:
            f=loginform
        context={'form':f}
        return render(request,'login.html',context)



    else:
        f=loginform
        context={'form':f}
        return render(request,'login.html',context)
    

def logout_view(request):
    logout(request)
    return redirect('/')    

from income.models import income
from expense.models import Expense
def get_balance(request):
    uid=request.session.get('uid')
    incl=income.objects.filter(user=uid)
    expl=Expense.objects.filter(user=uid)

    total_income=0
    total_expense=0

    for i in incl:
        total_income=total_income+i.income
    for i in expl:
        total_expense=total_expense+i.expense

    return total_income - total_expense        
    

project/project/Scripts/daily_income_expense/account/templates/add_expense.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>Add Expense</h1>

<form action="" method="post">
  {%csrf_token%}
<table border="1">
    <tr>
    <th><label for="id_expense">Expense:</label></th>
    <td>
      
      <input type="number" name="expense" required id="id_expense">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_expense_type">Expense type:</label></th>
    <td>
      
      <input type="text" name="expense_type" maxlength="30" required id="id_expense_type">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_expense_date">Expense date:</label></th>
    <td>
      
      <input type="text" name="expense_date" required id="id_expense_date">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_description">Description:</label></th>
    <td>
      
      <textarea name="description" cols="40" rows="10" maxlength="100" required id="id_description">
</textarea>
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_user">User:</label></th>
    <td><input type="text" value="{{user}}"></td>
  </tr>
    <tr>
        <td><input type="submit" value="save"></td>
        <td><input type="reset" value="reset"></td>
    </tr>
</table>
</form>
{%endblock%}

project/project/Scripts/daily_income_expense/account/templates/add_income.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>Add Income</h1>

<form action="" method="post">
    {%csrf_token%}
<table border="1">
    <tr>
    <th><label for="id_income">Income:</label></th>
    <td>
      
      <input type="number" name="income" required id="id_income">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_income_type">Income type:</label></th>
    <td>
      
      <input type="text" name="income_type" maxlength="30" required id="id_income_type">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_income_date">Income date:</label></th>
    <td>
      
      <input type="text" name="income_date" required id="id_income_date">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_description">Description:</label></th>
    <td>
      
      <textarea name="description" cols="40" rows="10" maxlength="100" required id="id_description">
</textarea>
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_user">User:</label></th>
    <td><input type="text" value="{{user}}"></td>
  </tr>
  <tr>
    <td><input type="submit" value="save"></td>
    <td><input type="reset" value="reset"></td>
  </tr>
{%endblock%}

project/project/Scripts/daily_income_expense/account/templates/exp_list.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>Expense List</h1>

<form action="{%url 'expense:expense_search'%}" method="post">
    {%csrf_token%}
    <textarea name="srch" id="" rows="1" cols="60"></textarea>
    <input type="submit" value="search">
</form>
{%if expl%}
<table border="1">
    <tr>
        <th>ID</th>
        <th>Expense</th>
        <th>Expense-type</th>
        <th>Expense-date</th>
        <th>Description</th>
        <th>User</th>
        <th colspan="2">Action</th>
    </tr>
    {%for i in expl%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.expense}}</td>
        <td>{{i.expense_type}}</td>
        <td>{{i.expense_date}}</td>
        <td>{{i.description}}</td>
        <td>{{i.user}}</td>
        <td><a href="delete1/{{i.id}}">delete</a></td>
    </tr>
    {%endfor%}
</table>
{%else%}
<h1>No Record Found..........</h1>
{%endif%}
<style>
.rside{
    width:250px;
    height: 100%;
    background-color: cadetblue;
    position: fixed;
    right: 0%;
    top: 0%;
}
h3{
    margin:20px;
    padding:20px;
}
.rside a{
    text-decoration: none;
    color: black;
} 
</style>
<div class="rside">
    <h2>Short By Expense_type</h2>
    <h3><a href="{%url 'expense:explist'%}">All</a></h3>
    {%for i in expt%}
    <h3><a href="{%url 'expense:ext1' i%}">{{i}}</a></h3>
    {%endfor%}
</div>
{%endblock%}

project/project/Scripts/daily_income_expense/account/templates/home.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>Daily Income Expense</h1>
<h2 style="color: rgb(4, 34, 95); font-family: cursive;">Welcome: {{user}}</h2>
<h2 style="color: rgb(4, 34, 95); font-family: cursive;">Total Balance:{{bal}}</h2>
{%endblock%}

project/project/Scripts/daily_income_expense/account/templates/inc_list.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>Income List</h1>

<form action="{%url 'income:income_search'%}" method="post">
    {%csrf_token%}
    <textarea name="srch" id="" rows="1" cols="60"></textarea>
    <input type="submit" value="search">
</form>

<table border="1">
    <tr>
        <th>ID</th>
        <th>Income</th>
        <th>Income-type</th>
        <th>Income-date</th>
        <th>Description</th>
        <th>User</th>
        <th colspan="2">Action</th>
    </tr>
    {%for i in incl%}
    <tr>
        <td>{{i.id}}</td>
        <td>{{i.income}}</td>
        <td>{{i.income_type}}</td>
        <td>{{i.income_date}}</td>
        <td>{{i.description}}</td>
        <td>{{i.user}}</td>
        <td><a href="delete/{{i.id}}">delete</a></td>
    </tr>
    {%endfor%}
</table>
<style>
.rside{
    width:250px;
    height: 100%;
    background-color: rgb(166, 225, 228);
    position: fixed;
    right: 0%;
    top: 0%;
}
h3{
    margin: 20px;
    padding: 20px;
}
.rside a{
    text-decoration: none;
    color: rgb(6, 26, 33);
} 
</style>
<div class="rside">
    <h2>Short By Income_type</h2>
    <h3><a href="{%url 'income:inclist'%}">All</a></h3>
    {%for i in inct%}
    <h3><a href="{%url 'income:inct1' i%}">{{i}}</a></h3>
    {%endfor%}
</div>
{%endblock%}

project/project/Scripts/daily_income_expense/account/templates/login.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>Login Form</h1>

<form action="" method="post">
    {%csrf_token%}
    <table border="1">
        {{form.as_table}}
        <tr>
            <td><input type="submit" value="save"></td>
            <td><input type="reset" value="reset"></td>
        </tr>
    </table>
</form>
{%endblock%}

project/project/Scripts/daily_income_expense/account/templates/reg.html
{%extends 'sidebar.html'%}
{%block body%}
<h1>Registration Form</h1>

<form action="" method="post">
    {%csrf_token%}
<table border="1">
    {{form.as_table}}
    <tr>
        <td><input type="submit" value="save"></td>
        <td><input type="reset" value="reset"></td>
    </tr>
</table>
</form>
{%endblock%}

project/project/Scripts/daily_income_expense/account/templates/sidebar.html
{%load static%}
<link rel="stylesheet" href="{%static 'css/style.css'%}">
<div class="side">
    {%if user.is_authenticated%}
    <h2><a href="{%url 'income:addinc'%}">Add Income</a></h2>
    <h2><a href="{%url 'expense:addexp'%}">Add Expense</a></h2>
    <h2><a href="{%url 'income:inclist'%}">Income List</a></h2>
    <h2><a href="{%url 'expense:explist'%}">Expense List</a></h2>
    <h2><a href="{%url 'account:logout'%}">Logout</a></h2> 
    <h2><a href="">Edit profile</a></h2>
    {%else%}
    <h2><a href="{%url 'account:reg'%}">Registration</a></h2>
    <h2><a href="{%url 'account:login'%}">Login</a></h2>
    {%endif%}
    
    <h2><a href="/">Home</a></h2> 
    <h2><a href="">About Us</a></h2>
</div>


<div class="main">
    {%block body%}
    {%endblock%}
</div>